# -*- coding: utf-8 -*-
"""
/***************************************************************************
 produceTrainingDataForDeepLearning
                                 A QGIS plugin
 The plugin fragments the remote sensing image, to be used as deep learning training datasets.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-26
        copyright            : (C) 2019 by Pratyush Tripathy
        email                : pratkrt@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load produceTrainingDataForDeepLearning class from file produceTrainingDataForDeepLearning.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .produce_training_data_for_deep_learning import produceTrainingDataForDeepLearning
    return produceTrainingDataForDeepLearning(iface)
